voice-pbx: support for uploading custom sound files for IVR, refs #3809

diff --git a/applications/luci-voice-pbx/root/etc/init.d/voice_pbx b/applications/luci-voice-pbx/root/etc/init.d/voice_pbx
--- a/applications/luci-voice-pbx/root/etc/init.d/voice_pbx
+++ b/applications/luci-voice-pbx/root/etc/init.d/voice_pbx
@@ -638,10 +638,10 @@ configure_ivr()
 	done
 
 	if [ $num_selections -eq 0 ] ; then
-		echo "exten => s,1,Playback(/usr/lib/asterisk/recordings/$sound_file)" >>	$WORKDIR/ivrs.tmp
+		echo "exten => s,1,Playback($sound_file)" >>					$WORKDIR/ivrs.tmp
 		echo "exten => s,n,Goto(hangup,h,2)" >>						$WORKDIR/ivrs.tmp
 	else
-		echo "exten => s,1,Background(/usr/lib/asterisk/recordings/$sound_file)" >>	$WORKDIR/ivrs.tmp
+		echo "exten => s,1,Background($sound_file)" >>					$WORKDIR/ivrs.tmp
 		echo "exten => s,n,WaitExten(10)" >>						$WORKDIR/ivrs.tmp
 		echo "exten => i,1,Goto($1,s,1)" >>						$WORKDIR/ivrs.tmp
 		echo "exten => t,1,Goto($1,s,1)" >>						$WORKDIR/ivrs.tmp
@@ -1382,66 +1382,105 @@ configure_language()
 	config_get voice_pack language voice_pack
 
 	if [ -z "$voice_pack" ] ; then
-		return
+		return 1
 	fi
-
+	
+	dstpath="/usr/lib/asterisk"
 	if [ -f $voice_pack ]; then
-		# Move voice-pack to /usr/lib/asterisk
+		workdir=`mktemp -d`
 		echo "Found new voice-pack"
-		path="/usr/lib/asterisk"
-		mv $voice_pack $path
-		filename=$(basename $voice_pack)
-		echo "Verifying voice-pack"
+		unpack_archive $voice_pack "sounds" $workdir
+		if [ $? -eq 0 ] ; then
+			if [ -d "$dstpath/sounds" ]; then
+				# Remove existing voice-pack
+				echo "Permanently removing old voice-pack"
+				rm -rf $dstpath/sounds
+			fi
+			# Install new voice-pack
+			echo "Installing new voice-pack"
+			mv $workdir/sounds $dstpath
+		else
+			echo "Unpack failed"
+		fi
+		# Clean-up
+		rm -rf $workdir
+	fi
+}
+
+#
+# Unpack archive of type tar.gz containing a single file or directory
+# 
+# $1 : Absolute path to archive
+# $2 : Name of contained file/dir
+# $3 : Destination path
+#
+unpack_archive()
+{
+	archive=$1
+
+	if [ -f $archive ]; then
+		# Move archive to tmp workdir
+		extractdir=`mktemp -d`
+		mv $archive $extractdir
+		filename=$(basename $archive)
+		echo "Verifying archive"
 		# Check if valid gzip archive
-		gunzip -t $path/$filename 2>/dev/null
+		gunzip -t $extractdir/$filename 2>/dev/null
 		if [ $? -ne 0 ] ; then
 			# Corrupt file or not a gzip archive
-			echo "Corrupt or incorrectly compressed voice-pack"
+			echo "Corrupt or incorrectly compressed archive"
 			# Remove it
-			rm $path/$filename
-			return
+			rm $extractdir/$filename
+			rm -rf $extractdir
+			return 1
 		fi
 		# Decompress
-		mv $path/$filename $path/voicepack.tar.gz
-		gunzip -f $path/voicepack.tar.gz 2>/dev/null
+		mv $extractdir/$filename $extractdir/archive.tar.gz
+		gunzip -f $extractdir/archive.tar.gz 2>/dev/null
 		if [ $? -ne 0 ] ; then
 			# Decompress failed
-			rm $path/voicepack.tar.gz
-			return
+			rm $extractdir/archive.tar.gz
+			rm -rf $extractdir
+			return 1
 		fi
-		# Make sure the tarball contains just a directory named sounds
+		# Make sure the tarball contains just a single file or directory
 		valid=1
 		listing=$(mktemp)
-		tar -tf $path/voicepack.tar > $listing 2>/dev/null
+		tar -tf $extractdir/archive.tar > $listing 2>/dev/null
 		if [ $? -ne 0 ] ; then
 			# Something went wrong
-			echo "Voice-pack not a compressed tarball"
-			rm $path/voicepack.tar
-			return
+			echo "Archive is not a compressed tarball"
+			rm $extractdir/archive.tar
+			rm -rf $extractdir
+			return 1
 		fi
 		while read i
 		do
-			# Each file in listing should start with 'sounds/'
-			if [ $(echo $i | sed 's/sounds\///') = $i ] ; then
+			# Each path in listing should start with '$2/'
+			len=${#2}
+			len=$((len+1))
+			if ! [ "x${i:0:$len}" == "x$2/" ] ; then
 				valid=0
 				break
 			fi
 		done < $listing
 		rm -f $listing
 		if [ $valid -eq 0 ] ; then
-			echo "Invalid voice-pack"
-			rm $path/voicepack.tar
-			return
+			echo "Invalid archive"
+			rm $extractdir/archive.tar
+			rm -rf $extractdir
+			return 1
 		fi
-		# Remove existing voice-pack
-		echo "Permanently removing old voice-pack"
-		rm -rf $path/sounds
-		# Unpack
-		echo "Installing voice-pack"
-		tar -xf $path/voicepack.tar 2>/dev/null
+		# Extract
+		echo "Extracting archive"
+		cd $3 >/dev/null
+		tar -xf $extractdir/archive.tar 2>/dev/null
+		cd - >/dev/null
 		# Clean-up
-		rm -f voicepack.tar voicepack.tar.gz
+		rm -f archive.tar archive.tar.gz
 	fi
+	rm -rf $extractdir
+	return 0
 }
 
 configure_moh()
@@ -1461,6 +1500,37 @@ configure_moh()
 		if [ $? == 0 ] ; then
 			echo "Installed new MOH sound file as music.gsm"
 		fi
+	fi
+}
+
+configure_custom_sounds()
+{
+	local sound_pack
+	config_get sound_pack custom_sounds sound_pack
+
+	if [ -z "$sound_pack" ] ; then
+		return 1
+	fi
+	
+	dstpath="/usr/lib/asterisk"
+	if [ -f $sound_pack ]; then
+		workdir=`mktemp -d`
+		echo "Found new custom sound-pack"
+		unpack_archive $sound_pack "custom" $workdir
+		if [ $? -eq 0 ] ; then
+			if [ -d "$dstpath/custom" ]; then
+				# Remove existing custom sound-pack
+				echo "Permanently removing old custom sound-pack"
+				rm -rf $dstpath/custom
+			fi
+			# Install new custom sound-pack
+			echo "Installing new custom sound-pack"
+			mv $workdir/custom $dstpath
+		else
+			echo "Unpack failed"
+		fi
+		# Clean-up
+		rm -rf $workdir
 	fi
 }
 
@@ -1643,6 +1713,11 @@ start() {
 	# Music on hold
 	###############
 	configure_moh
+
+	###############
+	# Custom Sounds
+	###############
+	configure_custom_sounds
 
 	####################
 	# Log configuration
